### ISSUE TITLE
Refactor name data repositories

### ISSUE THREAD

**Issue by rwongone** [Nosajool/Reddit-Anonymizer#5]
In branch feature/name-swap commit 2161e3d899a5630e58ffabbda3bc3c81fee40611, different name sets are given different variable names. This will not scale as the number of name sets increases. We could look into using a single database (columns: thingTheNameIsFrom, name) or try to use a hash mapping names of things to anonymous hashes or sets of names.

**Comment by Nosajool** [comment]
Merged in #8
